version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/tasks.json:/app/tasks.json
    restart: unless-stopped
    container_name: task-backend

  frontend:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./frontend/index.html:/usr/share/nginx/html/index.html
    restart: unless-stopped
    container_name: task-frontend
