pipeline {
    agent any
    
    environment {
        APP_DIR = '/home/ec2-user/aws-cicd-terraform-project/app'
    }
    
    stages {
        stage('Checkout') {
            steps {
                echo 'Pulling latest code from GitHub...'
                git branch: 'main', 
                    url: 'https://github.com/tarun08-code/aws-cicd-terraform-project.git'
            }
        }
        
        stage('Stop Old Containers') {
            steps {
                echo 'Stopping existing containers...'
                sh '''
                    docker stop task-backend task-frontend || true
                    docker rm task-backend task-frontend || true
                '''
            }
        }
        
        stage('Build Backend') {
            steps {
                echo 'Building backend Docker image...'
                sh '''
                    cd app/backend
                    docker build -t task-backend .
                '''
            }
        }
        
        stage('Deploy') {
            steps {
                echo 'Starting new containers...'
                sh '''
                    docker run -d --name task-backend -p 5000:5000 task-backend
                    docker run -d --name task-frontend -p 80:80 -v /var/lib/jenkins/workspace/DevOps-Deploy-Pipeline/app/frontend/index.html:/usr/share/nginx/html/index.html nginx:alpine
                '''
            }
        }
        
        stage('Health Check') {
            steps {
                echo 'Checking application health...'
                sh '''
                    sleep 5
                    curl -f http://localhost:5000/health || exit 1
                '''
            }
        }
    }
    
    post {
        success {
            echo '✅ Deployment successful!'
        }
        failure {
            echo '❌ Deployment failed!'
        }
    }
}
